version: '3'
services:
  server:
    build: ./server
    volumes:
      - .:/usr/server/
      - /usr/server/node_modules
    ports:
      - "8080:8080"
  client:
    build: ./client
    volumes:
      - .:/usr/client/
      - /usr/client/node_modules
    ports:
      - "3000:3000"